// Run against tsc output; no browser, model, token or database is involved.
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
const directory=process.argv[2];
const {prepare}=await import(pathToFileURL(directory+'/client.js'));
const {operations}=await import(pathToFileURL(directory+'/operations.js'));
const op=operations.knowledge_get_api_v1_pages_by_page_id;
assert.equal(prepare(op,{path:{page_id:'a/b?x=1%'}}).path,'/api/v1/pages/a%2Fb%3Fx%3D1%25');
for(const input of [{path:{page_id:'..'}},{path:{page_id:'ok'},query:{principal:'admin'}},{path:{page_id:'ok'},headers:{Authorization:'forged'}}]) assert.throws(()=>prepare(op,input));
const authorize=operations.auth_post_internal_v1_authorize;
const body={action:'read',space_id:'s'};
const request=prepare(authorize,{body});body.space_id='changed';
assert.equal(request.body,'{"action":"read","space_id":"s"}');
assert.throws(()=>prepare(authorize,{body:{value:NaN}}));
assert.equal('token' in request,false);
assert.equal(operations.retrieval_post_api_v1_search.response_typing,'typed');
assert.ok(operations.retrieval_post_api_v1_search.response_schema.endsWith('/post/responses'));
assert.equal(operations.knowledge_get_api_v1_pages_by_page_id_lifecycle.response_schema,null);
assert.equal(operations.llm_post_internal_v1_chat.transport,'http-json-or-sse');
assert.equal(operations.agent_get_api_v1_runs_by_run_id_events.transport,'sse');
console.log('TypeScript client boundary checks passed');
const fence={'X-Ingest-Source-Id':'git:test','X-Ingest-Generation':'1'};
const publish=operations.knowledge_post_internal_v1_pages_publish;
assert.equal(prepare(publish,{body:{},headers:fence}).headers['X-Ingest-Generation'],'1');
assert.throws(()=>prepare(publish,{body:{}}));
assert.throws(()=>prepare(operations.gateway_post_api_v1_pages,{body:{},headers:fence}));
const stream=operations.agent_get_api_v1_runs_by_run_id_events;
assert.equal(prepare(stream,{path:{run_id:'r'},query:{cursor:1},headers:{'Last-Event-ID':'4'}}).headers['Last-Event-ID'],'4');
assert.throws(()=>prepare(stream,{path:{run_id:'r'},headers:{'Last-Event-ID':'4','last-event-id':'5'}}));
assert.equal(operations.iam_delete_api_v1_service_accounts_by_id.transport,'http-empty');
console.log('TypeScript native fence/resume/204 checks passed');
