#!/usr/bin/env python3
"""Generate the Go operations table from the published OpenAPI contracts.

The contracts under contracts/generated/openapi are the single source of truth.
This script never edits service handlers; it only emits the request-preparation
table consumed by internal/generatedcontracts/client.go.

    python3 knowledge-docker/scripts/contract_generate.py
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OPENAPI_DIR = ROOT / "contracts" / "generated" / "openapi"
OUTPUT = ROOT / "services" / "go" / "internal" / "generatedcontracts" / "operations.go"

METHODS = ("get", "post", "put", "patch", "delete", "head", "options")


def schema_name(schema: object) -> str:
    """Best-effort schema identifier; empty when the schema is inline."""
    if not isinstance(schema, dict):
        return ""
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return ref.rsplit("/", 1)[-1]
    return ""


def response_schema(operation: dict) -> str:
    responses = operation.get("responses") or {}
    for status in sorted(responses, key=str):
        if not str(status).startswith("2"):
            continue
        content = (responses[status] or {}).get("content") or {}
        for media in sorted(content):
            if "json" not in media:
                continue
            name = schema_name((content[media] or {}).get("schema"))
            if name:
                return name
    return ""


def request_schema(operation: dict) -> str:
    body = operation.get("requestBody") or {}
    content = body.get("content") or {}
    for media in sorted(content):
        if "json" in media:
            return schema_name((content[media] or {}).get("schema"))
    return ""


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def go_strings(values: list[str]) -> str:
    if not values:
        return "nil"
    return "[]string{" + ", ".join(go_string(v) for v in values) + "}"


def collect() -> tuple[dict[str, dict], int]:
    operations: dict[str, dict] = {}
    skipped = 0
    for path in sorted(OPENAPI_DIR.glob("*.json")):
        service = path.stem
        document = json.loads(path.read_text(encoding="utf-8"))
        for template, methods in sorted((document.get("paths") or {}).items()):
            if not isinstance(methods, dict):
                continue
            for method in METHODS:
                operation = methods.get(method)
                if not isinstance(operation, dict):
                    continue
                identifier = operation.get("operationId")
                if not identifier:
                    skipped += 1
                    continue
                path_parameters: list[str] = []
                query_parameters: list[str] = []
                header_parameters: list[str] = []
                required_headers: list[str] = []
                for parameter in operation.get("parameters") or []:
                    if not isinstance(parameter, dict):
                        continue
                    location = parameter.get("in")
                    name = parameter.get("name")
                    if not name:
                        continue
                    if location == "path":
                        path_parameters.append(name)
                    elif location == "query":
                        query_parameters.append(name)
                    elif location == "header":
                        header_parameters.append(name)
                        if parameter.get("required"):
                            required_headers.append(name)
                body = operation.get("requestBody")
                body = body if isinstance(body, dict) else {}
                operations[identifier] = {
                    "id": identifier,
                    "service": operation.get("x-service") or service,
                    "method": method.upper(),
                    "template": template,
                    "response_typing": operation.get("x-response-typing") or "typed",
                    "transport": operation.get("x-transport") or "http-json",
                    "path_parameters": path_parameters,
                    "query_parameters": query_parameters,
                    "header_parameters": header_parameters,
                    "required_header_parameters": required_headers,
                    "body_required": bool(body.get("required")),
                    "accepts_body": bool(body),
                    "request_schema": request_schema(operation),
                    "response_schema": response_schema(operation),
                }
    return operations, skipped


def render(operations: dict[str, dict]) -> str:
    lines = [
        "// Generated by knowledge-docker/scripts/contract_generate.py; DO NOT EDIT.",
        "// Source of truth: contracts/generated/openapi/*.json",
        "",
        "package generatedcontracts",
        "",
        "// Operations indexes every published operation by its contract operation id.",
        "var Operations = map[string]Operation{",
    ]
    for identifier in sorted(operations):
        op = operations[identifier]
        lines += [
            f"\t{go_string(identifier)}: {{",
            f"\t\tID: {go_string(op['id'])}, Service: {go_string(op['service'])}, "
            f"Method: {go_string(op['method'])}, Template: {go_string(op['template'])}, "
            f"ResponseTyping: {go_string(op['response_typing'])}, Transport: {go_string(op['transport'])},",
            f"\t\tPathParameters: {go_strings(op['path_parameters'])}, "
            f"QueryParameters: {go_strings(op['query_parameters'])},",
            f"\t\tHeaderParameters: {go_strings(op['header_parameters'])}, "
            f"RequiredHeaderParameters: {go_strings(op['required_header_parameters'])},",
            f"\t\tBodyRequired: {'true' if op['body_required'] else 'false'}, "
            f"AcceptsBody: {'true' if op['accepts_body'] else 'false'},",
            f"\t\tRequestSchema: {go_string(op['request_schema'])}, "
            f"ResponseSchema: {go_string(op['response_schema'])},",
            "\t},",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    if not OPENAPI_DIR.is_dir():
        print(f"contracts directory not found: {OPENAPI_DIR}", file=sys.stderr)
        return 1
    operations, skipped = collect()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(operations), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(operations)} operations"
          + (f" ({skipped} skipped: missing operationId)" if skipped else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
