import { useEffect,useRef,useState } from "react";
import { Alert,Button,Card,Checkbox,Descriptions,Drawer,Empty,Form,Input,List,Modal,Popconfirm,Select,Space,Steps,Switch,Tabs,Tag,Typography } from "antd";
import { Link,useSearchParams } from "react-router-dom";
import { useAuth } from "../auth";
import { ApiError,pathId,query } from "../api";
import { useResource } from "../hooks";
import { useAgentList } from "../agent-hooks";
import { useChannelResource } from "../channel-hooks";
import { canEnable,channelConfig,channelGroup,channelKeyPattern,channelList,channelMessage,configInput,connectionState,groupState } from "../channel-api";
import type { ChannelConfig,ChannelGroup,ChannelInput } from "../channel-types";
import type { AgentDefinition } from "../agent-types";
import type { Principal,Space as KnowledgeSpace } from "../types";
import { ErrorNotice,formatDate,PageHeader,RefreshButton,ResourceView } from "../components/Common";
export function ChannelsPage({principal}:{principal:Principal}){return <><PageHeader eyebrow="CONNECTED CHANNELS" title="企业微信渠道" description="将已发布智能体接入企微，分别设置个人身份与群受众权限。" extra={<Link to="/channels/bindings">我的账号绑定</Link>}/>{principal.permissions.includes("platform_admin")?<ChannelsPanel/>:<Alert type="info" message="管理机器人渠道需要平台管理权限。个人账号绑定不需要此权限。"/>}</>;}
export function ChannelsPanel(){
 const {api}=useAuth();const [params,setParams]=useSearchParams();const selected=params.get("channel")??"";
 const channels=useChannelResource("channels",async signal=>channelList(await api.get("/channels",signal),channelConfig));
 const [creating,setCreating]=useState(false);
 const close=()=>{const next=new URLSearchParams(params);next.delete("channel");setParams(next);};
 return <><div className="section-toolbar"><Typography.Text type="secondary">保存停用配置后检测连接，再复核范围并启用。最多显示 100 个渠道。</Typography.Text><Space><RefreshButton onClick={channels.refresh}/><Button type="primary" onClick={()=>setCreating(true)}>添加企微机器人</Button></Space></div>
  <Alert type="info" showIcon message="每个机器人保持一条主动长连接" description="请先在企微创建 AI Bot 并取得 BotID 与 BotSecret。首次私聊通过 /绑定 关联平台账号；群聊还需要管理员单独授权。"/>
  <ResourceView resource={channels}>{items=><div className="channel-grid">{items.length===0?<Empty description="尚未配置企微机器人"/>:items.map(c=><Card key={c.id} title={c.name} extra={<Tag color={c.enabled&&c.status==="connected"?"green":"default"}>{connectionState(c)}</Tag>}><Typography.Paragraph type="secondary">BotID：{c.bot_id}</Typography.Paragraph><Space wrap><Tag>配置 v{c.version}</Tag><Tag>{c.space_ids.length} 个空间</Tag><Tag>{c.secret_configured?"凭据已配置":"缺少凭据"}</Tag></Space><div className="form-footer"><Button onClick={()=>{const next=new URLSearchParams(params);next.set("channel",c.id);setParams(next);}}>管理 {c.name}</Button></div></Card>)}</div>}</ResourceView>
  {creating&&!channels.error&&<ChannelEditor agentHint={params.get("agent")??undefined} onClose={()=>setCreating(false)} onSaved={c=>{setCreating(false);channels.refresh();const next=new URLSearchParams(params);next.set("channel",c.id);setParams(next);}}/>}
  <Drawer open={!!selected} width={960} title="渠道配置与运行状态" onClose={close} destroyOnHidden>{selected&&<ChannelDetail key={selected} id={selected} onChanged={channels.refresh}/>}</Drawer>
 </>;
}
function ChannelDetail({id,onChanged}:{id:string;onChanged:()=>void}){
 const {api}=useAuth();const config=useChannelResource(`channel:${id}`,async signal=>channelConfig(await api.get(`/channels/${pathId(id)}`,signal)),3000);const [editing,setEditing]=useState(false);
 const refresh=()=>{config.refresh();onChanged();};
 return <ResourceView resource={config}>{c=><><Descriptions column={2} items={[{key:"name",label:"名称",children:c.name},{key:"bot",label:"BotID",children:c.bot_id},{key:"version",label:"渠道版本",children:`v${c.version}`},{key:"config",label:"固定智能体配置",children:<Link to={`/agents${query({agent:c.agent_id,configuration:c.agent_configuration_id})}`}>{c.agent_configuration_id}</Link>}]}/><Tabs destroyOnHidden items={[{key:"connection",label:"连接与范围",children:<><ChannelConnection config={c} onChanged={refresh}/><Typography.Title level={5}>渠道知识范围</Typography.Title><Space wrap>{c.space_ids.map(id=><Tag key={id}>{id}</Tag>)}</Space><div className="form-footer"><Button onClick={()=>setEditing(true)}>编辑配置</Button></div></>},{key:"groups",label:"群授权",children:<ChannelGroups config={c}/>},{key:"diagnostics",label:"消息与诊断",children:<ChannelDiagnostics id={c.id}/>} ]}/>{editing&&<ChannelEditor config={c} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);refresh();}}/>}</>}</ResourceView>;
}
export function ChannelConnection({config:c,onChanged}:{config:ChannelConfig;onChanged:()=>void}){
 const {api}=useAuth();const [busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[accepted,setAccepted]=useState(false);const live=useRef(true);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const act=async(test:boolean)=>{if(busy)return;setBusy(true);setError(undefined);try{if(test){const v=await api.post<{status:string}>(`/channels/${pathId(c.id)}/test`,{base_version:c.version});if(v.status!=="test_pending")throw new ApiError(502,"invalid_test_response");if(live.current)setAccepted(true);}else{channelConfig(await api.put(`/channels/${pathId(c.id)}`,configInput(c,!c.enabled)));}}catch(e){if(live.current)setError(e);}finally{if(live.current){setBusy(false);onChanged();}}};
 return <div className="channel-stack"><Steps size="small" current={c.enabled?3:canEnable(c)?2:1} items={[{title:"保存配置"},{title:"检测连接"},{title:"复核范围"},{title:"启用渠道"}]}/><Alert type={c.status==="connected"&&c.enabled?"success":"info"} showIcon message={connectionState(c)} description={c.enabled?"机器人仅在连接成功、身份绑定和当前授权同时有效时接受问答。":"当前渠道停用。检测只验证订阅握手，不执行消息问答。"}/>{accepted&&c.status==="disabled"&&<Alert type="info" message="检测请求已提交，等待 worker 写回实际连接结果。"/>}{c.status==="displaced"&&<Alert type="warning" message="请检查是否有其他实例使用同一 BotID。修改并保存配置后，才能解除隔离并重新检测。"/>}<ErrorNotice error={error}/><Space wrap><Button disabled={c.enabled||c.status==="test_pending"||busy||accepted} loading={busy} onClick={()=>void act(true)}>检测连接</Button><Popconfirm title={c.enabled?"停用此机器人？":"确认启用当前配置与知识范围？"} description={c.enabled?"现有连接与上下文将失效。":"启用后仍需等待连接成功；群知识仅按独立授权开放。"} okText={c.enabled?"确认停用":"确认启用"} cancelText="取消" onConfirm={()=>act(false)}><Button type={c.enabled?"default":"primary"} danger={c.enabled} disabled={busy||(!c.enabled&&(!canEnable(c)||accepted))}>{c.enabled?"停用渠道":"启用渠道"}</Button></Popconfirm></Space><Typography.Text type="secondary">当前版本 {c.version} · 成功检测版本 {c.tested_version||"无"}。修改密钥后必须重新检测。</Typography.Text></div>;
}
export function ChannelEditor({config,agentHint,onClose,onSaved}:{config?:ChannelConfig;agentHint?:string;onClose:()=>void;onSaved:(c:ChannelConfig)=>void}){
 const {api}=useAuth();const agents=useAgentList<AgentDefinition>("/agents"),spaces=useAgentList<KnowledgeSpace>("/spaces");
 const [form]=Form.useForm<ChannelInput>();const [agentId,setAgentId]=useState(config?.agent_id??agentHint??"");
 const published=useResource(`channel-published:${agentId}`,async signal=>{if(!agentId)return null;const a=await api.get<AgentDefinition>(`/agents/${pathId(agentId)}`,signal);if(!a.shared||!a.published_configuration_id)throw new ApiError(409,"agent_not_published");const fixed=await api.get<AgentDefinition>(`/agents/${pathId(agentId)}${query({configuration_id:a.published_configuration_id})}`,signal);if(fixed.configuration_id!==a.published_configuration_id)throw new ApiError(502,"invalid_agent_configuration");return fixed;});
 const [busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const live=useRef(true);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const allowed=spaces.items.filter(s=>published.data?.config.space_ids.includes(s.id));
 const submit=async(v:ChannelInput)=>{if(busy||!published.data||!v.space_ids.every(id=>allowed.some(s=>s.id===id)))return;setBusy(true);setError(undefined);const input:ChannelInput={base_version:config?.version??0,name:v.name,bot_id:v.bot_id,bot_secret:v.bot_secret??"",agent_id:agentId,space_ids:v.space_ids,enabled:false};form.setFieldValue("bot_secret","");try{const raw=config?await api.put(`/channels/${pathId(config.id)}`,input):await api.post("/channels",input);const c=channelConfig(raw);if(live.current)onSaved(c);}catch(e){if(live.current)setError(e);}finally{if(live.current)setBusy(false);}};
 return <Modal open width={700} title={config?"编辑机器人配置":"添加企微机器人"} footer={null} onCancel={()=>{form.setFieldValue("bot_secret","");onClose();}} destroyOnHidden><Form form={form} layout="vertical" clearOnDestroy initialValues={{...config,agent_id:agentId,space_ids:config?.space_ids??[],bot_secret:""}} onFinish={v=>void submit(v)}>
  <Alert type="info" showIcon message={config?.enabled?"保存将停用当前渠道并更新版本":"配置先保存为停用状态"} description="先选择已共享发布的智能体和当前可读空间。BotSecret 只用于此次提交，不在浏览器保存或回显。"/>
  <Form.Item name="agent_id" label="已发布智能体" rules={[{required:true,message:"请选择已发布智能体"}]}><Select showSearch optionFilterProp="label" loading={agents.loading} onChange={id=>{setAgentId(id);form.setFieldValue("space_ids",[]);}} options={agents.items.filter(a=>a.shared&&a.published_configuration_id).map(a=>({value:a.id,label:a.name}))} placeholder="选择共享发布的配置"/></Form.Item>
  {agents.next&&<Button onClick={()=>void agents.more()}>加载更多智能体</Button>}
  {!agents.loading&&!agents.items.some(a=>a.shared&&a.published_configuration_id)&&<Alert type="info" message={<span>尚无已发布智能体。请先到 <Link to="/agents">智能体</Link> 创建并发布。</span>}/>}
  <ErrorNotice error={agents.error}/><ErrorNotice error={published.error}/>
  {published.data&&<Typography.Paragraph type="secondary">已发布配置：{published.data.configuration_id} · 服务端保存时会再次校验当前发布版本。</Typography.Paragraph>}
  <Form.Item name="name" label="渠道名称" rules={[{required:true,whitespace:true,message:"请输入渠道名称"},{validator:(_,v)=>!v||new TextEncoder().encode(v).length<=160?Promise.resolve():Promise.reject(new Error("渠道名称过长"))}]}><Input maxLength={160} autoComplete="off"/></Form.Item>
  <Form.Item name="bot_id" label="BotID" rules={[{required:true,message:"请输入企微 BotID"},{pattern:channelKeyPattern,message:"BotID 格式不正确"}]}><Input disabled={!!config} autoComplete="off"/></Form.Item>
  <Form.Item name="bot_secret" label={config?"替换 BotSecret（留空保留）":"BotSecret"} rules={[{required:!config,message:"请输入 BotSecret"},{validator:(_,v)=>!v||new TextEncoder().encode(v).length<=4096?Promise.resolve():Promise.reject(new Error("BotSecret 过长"))}]}><Input.Password autoComplete="new-password" visibilityToggle={false}/></Form.Item>
  <Form.Item name="space_ids" label="渠道知识范围" rules={[{required:true,type:"array",min:1,max:100,message:"请选择 1–100 个当前可读空间"}]} extra="机器人范围取用户、智能体、渠道和本轮授权的交集；群聊还受独立群受众约束。"><Select mode="multiple" loading={spaces.loading||published.loading} disabled={!published.data} options={allowed.map(s=>({label:s.name,value:s.id}))}/></Form.Item>
  {spaces.next&&<Button onClick={()=>void spaces.more()}>加载更多空间</Button>}<ErrorNotice error={spaces.error}/><ErrorNotice error={error}/>{error!=null&&String(error)&&<Typography.Paragraph>密钥输入已清除。若提交结果不确定，请关闭并刷新渠道列表核对，再决定是否重新提交。</Typography.Paragraph>}
  <div className="form-footer"><Button onClick={()=>{form.setFieldValue("bot_secret","");onClose();}}>取消</Button><Button type="primary" htmlType="submit" loading={busy} disabled={!published.data||!!spaces.error}>{config?.enabled?"保存并停用":"保存停用配置"}</Button></div>
 </Form></Modal>;
}
function GroupError({error}:{error:unknown}){if(error instanceof ApiError&&[403,409,503].includes(error.status))return <Alert showIcon type="error" message={error.status===409?"配置版本或远端授权发生冲突":error.status===403?"当前账号缺少群授权管理权限":"授权依赖暂不可用"} description="已重新读取群状态。请求可能已持久化为待同步操作；请核对当前版本和范围，再选择继续对账或重新编辑。"/>;return <ErrorNotice error={error}/>;}
export function ChannelGroups({config}:{config:ChannelConfig}){
 const {api}=useAuth();const groups=useChannelResource(`channel-groups:${config.id}:${config.version}`,async signal=>channelList(await api.get(`/channels/${pathId(config.id)}/groups`,signal),channelGroup));
 const [editing,setEditing]=useState<ChannelGroup|"new">(),[busy,setBusy]=useState<string>(),[error,setError]=useState<unknown>();const live=useRef(true);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const reconcile=async(g:ChannelGroup)=>{if(busy)return;setBusy(g.id);setError(undefined);try{channelGroup(await api.post(`/channels/${pathId(config.id)}/groups/${pathId(g.chat_id)}/reconcile`,{base_version:g.version}));}catch(e){if(live.current)setError(e);}finally{if(live.current){setBusy(undefined);groups.refresh();}}};
 return <div className="channel-stack"><Alert type="warning" showIcon message="群授权面向群内当前及后续成员" description="只登记已确认的企微群 ChatID，并为其明确选择可以在群中回答的知识空间。提问者的个人私有知识不会自动开放给群。"/><div className="section-toolbar"><Typography.Text type="secondary">手动登记群；ChatID 来自受控企微消息事件。本页不自动发现群。最多显示 100 条。</Typography.Text><Space><RefreshButton onClick={groups.refresh}/><Button onClick={()=>setEditing("new")}>登记群授权</Button></Space></div><GroupError error={error}/><ResourceView resource={groups}>{items=><List dataSource={items} locale={{emptyText:"尚未登记群；群聊不能执行知识问答"}} renderItem={g=>{const state=groupState(g);return <List.Item actions={[<Button key="edit" onClick={()=>setEditing(g)}>编辑 {g.chat_id}</Button>,...(g.sync_state==="pending"?[<Button key="reconcile" aria-label={`继续对账 ${g.chat_id}`} loading={busy===g.id} disabled={!!busy} onClick={()=>void reconcile(g)}>继续对账</Button>]:[])]}><List.Item.Meta title={<Space wrap>{g.chat_id}<Tag color={state.usable?"green":g.sync_state==="pending"?"gold":undefined}>{state.label}</Tag></Space>} description={<><div>渠道群版本 {g.version} · 授权版本 {g.audience_version} · 所请求状态：{g.desired_enabled?"启用":"禁用"}</div><div>所请求范围：{g.space_ids.join("、")}</div>{g.sync_error&&<div>同步诊断：{({audience_unavailable:"IAM 暂不可用",audience_denied:"授权被拒绝",audience_conflict:"远端授权版本冲突",legacy_reconciliation_required:"旧配置需要重新对账"} as Record<string,string>)[g.sync_error]??"需要重新核验授权"}</div>}</>}/></List.Item>;}}/>}</ResourceView>{editing&&!groups.error&&<GroupEditor config={config} group={editing==="new"?undefined:editing} onClose={()=>setEditing(undefined)} onRefresh={groups.refresh} onSaved={()=>{setEditing(undefined);groups.refresh();}}/>}</div>;
}
function GroupEditor({config,group,onClose,onRefresh,onSaved}:{config:ChannelConfig;group?:ChannelGroup;onClose:()=>void;onRefresh:()=>void;onSaved:()=>void}){
 const {api}=useAuth();const spaces=useAgentList<KnowledgeSpace>("/spaces");const [form]=Form.useForm();const enabled=Form.useWatch("enabled",form);const acknowledged=Form.useWatch("acknowledged_public_to_group",form);
 const [audience]=useState(()=>group?.audience_id??crypto.randomUUID());const [error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);const live=useRef(true);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const save=async(v:{chat_id:string;space_ids:string[];enabled:boolean;acknowledged_public_to_group:boolean})=>{if(busy||v.enabled&&!v.acknowledged_public_to_group)return;setBusy(true);setError(undefined);try{channelGroup(await api.put(`/channels/${pathId(config.id)}/groups/${pathId(v.chat_id)}`,{base_version:group?.version??0,audience_id:audience,space_ids:v.space_ids,enabled:v.enabled,acknowledged_public_to_group:!!v.acknowledged_public_to_group}));if(live.current)onSaved();}catch(e){if(live.current)setError(e);}finally{if(live.current){setBusy(false);onRefresh();}}};
 return <Modal open width={680} footer={null} title={group?"编辑群授权":"登记受控企微群"} onCancel={onClose} destroyOnHidden><Form form={form} clearOnDestroy layout="vertical" initialValues={{chat_id:group?.chat_id,space_ids:group?.space_ids??[],enabled:group?.desired_enabled??false,acknowledged_public_to_group:false}} onFinish={v=>void save(v)}><Alert type="warning" showIcon message="这项授权面向本群当前及后续成员" description="选择的空间仍受文档收紧与实时用户权限约束。请先确认群身份，勿用群名称代替 ChatID。"/><Form.Item name="chat_id" label="可信企微事件中的 ChatID" rules={[{required:true,message:"请输入确认过的 ChatID"},{pattern:channelKeyPattern,message:"ChatID 格式不正确"}]}><Input autoComplete="off" disabled={!!group}/></Form.Item><Form.Item label="群可公开知识范围" name="space_ids" rules={[{required:true,type:"array",min:1,max:100,message:"请选择 1–100 个空间"}]}><Select mode="multiple" loading={spaces.loading} options={spaces.items.filter(s=>config.space_ids.includes(s.id)).map(s=>({label:s.name,value:s.id}))}/></Form.Item>{spaces.next&&<Button onClick={()=>void spaces.more()}>加载更多空间</Button>}<ErrorNotice error={spaces.error}/><Form.Item name="enabled" label="所请求群状态" valuePropName="checked"><Switch checkedChildren="启用" unCheckedChildren="禁用"/></Form.Item>{enabled&&<Form.Item name="acknowledged_public_to_group" valuePropName="checked"><Checkbox>我确认所选知识可面向本群当前及后续成员提供，并已核对群身份。</Checkbox></Form.Item>}<Typography.Paragraph type="secondary">群授权需要每个空间的读取与授权管理权限。保存停用配置不会提前授予 IAM 读取权。{group&&`当前基础版本：${group.version}。`}</Typography.Paragraph><GroupError error={error}/><div className="form-footer"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={busy} disabled={!!spaces.error||enabled&&!acknowledged}>提交群配置</Button></div></Form></Modal>;
}
function ChannelDiagnostics({id}:{id:string}){
 const {api}=useAuth();const messages=useChannelResource(`channel-diagnostics:${id}`,async signal=>channelList(await api.get(`/channels/${pathId(id)}/diagnostics`,signal),channelMessage));
 return <><div className="section-toolbar"><Typography.Text type="secondary">最近 100 条接收与处理状态。发送结果未知时不会盲目重发，请检查运行或重新提问。</Typography.Text><RefreshButton onClick={messages.refresh}/></div><ResourceView resource={messages}>{items=><List dataSource={items} locale={{emptyText:"尚无消息记录；连接成功后可在企微私聊发送 /帮助"}} renderItem={m=><List.Item extra={m.run_id?<Link to={`/runs/${pathId(m.run_id)}`}>查看运行（需授权）</Link>:undefined}><List.Item.Meta title={<Space><Typography.Text code>{m.message_id}</Typography.Text><Tag>{m.state}</Tag></Space>} description={formatDate(m.created_at)}/></List.Item>}/>}</ResourceView></>;
}
