import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Button, Drawer, Input, List, Select, Space, Tabs, Typography } from 'antd';
import { useAuth } from '../auth';
import { pathId, query } from '../api';
import { useMutation, useResource } from '../hooks';
import type { EvidenceRef, ListResult, Proposal, Revision, Space as KnowledgeSpace } from '../types';
import { ContentDiff, SafeMarkdown } from '../components/Content';
import { CitationDrawer, EvidenceList } from '../components/Citation';
import { ErrorNotice, formatDate, PageHeader, RefreshButton, ResourceView, StatusTag } from '../components/Common';
import { allEvidence } from './Wiki';
import { ServiceRecords } from './Experience';
export function ReviewsPage(){return <><PageHeader eyebrow="OPERATIONS" title="任务与审核" description="追踪实际处理结果，并审阅会改变正式知识的提案。"/><Tabs destroyOnHidden items={[{key:'reviews',label:'知识审核',children:<ReviewList/>},{key:'tasks',label:'接入任务',children:<ServiceRecords path="/tasks" title="暂无接入任务" description="接入服务就绪后，此处展示真实任务的处理状态与失败原因。"/>}]}/></>;}
function ReviewList(){const {api}=useAuth();const [status,setStatus]=useState('pending'),[spaceId,setSpaceId]=useState<string>(),[cursor,setCursor]=useState<string>(),[selected,setSelected]=useState<Proposal>();const spaces=useResource('review-spaces',signal=>api.get<ListResult<KnowledgeSpace>>('/spaces',signal));const reviews=useResource(`reviews:${spaceId}:${status}:${cursor}`,signal=>api.get<ListResult<Proposal>>(`/reviews${query({space_id:spaceId,status,cursor,limit:50})}`,signal));return <><div className="section-toolbar"><Space wrap><Select aria-label="审核状态" value={status} onChange={value=>{setStatus(value);setCursor(undefined);setSelected(undefined);}} options={[{value:'pending',label:'待审核'},{value:'approved',label:'已批准'},{value:'rejected',label:'已拒绝'}]}/><Select aria-label="审核空间" allowClear placeholder="全部可读空间" value={spaceId} onChange={value=>{setSpaceId(value);setCursor(undefined);setSelected(undefined);}} loading={spaces.loading} options={spaces.data?.items.map(s=>({value:s.id,label:s.name}))} style={{minWidth:180}}/></Space><RefreshButton onClick={()=>{setSelected(undefined);reviews.refresh();spaces.refresh();}}/></div><ErrorNotice error={spaces.error}/><ResourceView resource={reviews}>{data=><><List className="panel" locale={{emptyText:'当前范围没有可审核的提案。审核列表受实时内容与审核权限过滤。'}} dataSource={data.items} renderItem={proposal=><List.Item actions={[<Button key="review" onClick={()=>setSelected(proposal)}>查看提案</Button>]}><List.Item.Meta title={<Space>{proposal.content.title}<StatusTag status={proposal.status}/></Space>} description={<>{proposal.reason}<div className="muted">{formatDate(proposal.created_at)} · {proposal.proposed_by}</div></>}/></List.Item>}/><div className="pagination"><Button disabled={!cursor} onClick={()=>setCursor(undefined)}>第一页</Button><Button disabled={!data.next_cursor} onClick={()=>setCursor(data.next_cursor??undefined)}>下一页</Button></div></>}</ResourceView><Drawer width={960} open={!!selected} title="审核知识变更" onClose={()=>setSelected(undefined)} destroyOnHidden>{selected&&<ReviewBody key={selected.id} proposal={selected} onResolved={()=>{setSelected(undefined);reviews.refresh();}}/>}</Drawer></>;}
function ReviewBody({proposal,onResolved}:{proposal:Proposal;onResolved:()=>void}){const {api}=useAuth();const [reason,setReason]=useState(''),[citation,setCitation]=useState<EvidenceRef|null>(null);const base=useResource(`proposal-base:${proposal.id}`,signal=>proposal.base_revision?api.get<Revision>(`/pages/${pathId(proposal.page_id)}/revisions/${pathId(proposal.base_revision)}`,signal):Promise.resolve(null));const mutation=useMutation();return <><Space><StatusTag status={proposal.status}/><Link to={`/pages/${pathId(proposal.page_id)}`}>查看当前 Wiki</Link></Space><Typography.Title level={3}>{proposal.content.title}</Typography.Title><Typography.Paragraph>{proposal.reason}</Typography.Paragraph><Typography.Text type="secondary">提案类型：{proposal.kind} · 基准版本：{proposal.base_revision??'首次发布'}</Typography.Text><ResourceView resource={base}>{revision=><><Tabs items={[{key:'diff',label:'正文差异',children:<ContentDiff before={revision?.content.markdown??''} after={proposal.content.markdown}/>},{key:'preview',label:'修改后预览',children:<SafeMarkdown text={proposal.content.markdown}/>},{key:'full',label:'完整内容差异',children:<ContentDiff before={JSON.stringify(revision?.content??{},null,2)} after={JSON.stringify(proposal.content,null,2)}/>} ]}/><Typography.Title level={5}>提案证据</Typography.Title><EvidenceList evidence={allEvidence(proposal.content)} onSelect={setCitation}/>{proposal.status==='pending'?<div className="review-actions"><Alert type="info" message="批准前会重新检查权限、原始证据与基准版本。版本变化时提案保持待审核，不会覆盖最新内容。"/><Input.TextArea aria-label="审核意见" placeholder="填写审核理由（必填）" value={reason} onChange={event=>setReason(event.target.value)} maxLength={4096}/><ErrorNotice error={mutation.error}/><Space><Button danger disabled={!reason.trim()} loading={mutation.busy} onClick={()=>void mutation.run(()=>api.post(`/reviews/${pathId(proposal.id)}/reject`,{reason}),onResolved)}>拒绝提案</Button><Button type="primary" disabled={!reason.trim()} loading={mutation.busy} onClick={()=>void mutation.run(()=>api.post(`/reviews/${pathId(proposal.id)}/approve`,{reason}),onResolved)}>批准并发布</Button></Space></div>:<Typography.Paragraph>审核意见：{proposal.review_reason??'—'}</Typography.Paragraph>}</>}</ResourceView><CitationDrawer evidence={citation} onClose={()=>setCitation(null)}/></>;}