import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Button, Collapse, Descriptions, Drawer, Form, Input, List, Modal, Popconfirm, Select, Space, Switch, Tabs, Tag, Typography } from 'antd';
import { CloudSyncOutlined, EyeOutlined, FileOutlined, PlusOutlined } from '@ant-design/icons';
import { useAuth } from '../auth';
import { ApiError, pathId, query } from '../api';
import { useMutation, useResource } from '../hooks';
import type { IngestTask, ListResult, SourcePreview, SourceRecord } from '../types';
import { ErrorNotice, formatDate, RefreshButton, ResourceView } from '../components/Common';
const taskLabels:Record<string,string>={queued:'排队中',running:'处理中',succeeded:'已完成',review_needed:'需要审核',superseded:'已被更新版本替代',failed:'失败'};
export function SourcesPanel({spaceId,onManageACL}:{spaceId:string;onManageACL?:()=>void}){
 const {api}=useAuth();const [cursor,setCursor]=useState<string>(),[editing,setEditing]=useState<SourceRecord|'new'>(),[selected,setSelected]=useState<SourceRecord>(),[filter,setFilter]=useState('');
 const sources=useResource(`sources:${spaceId}:${cursor}`,signal=>api.get<ListResult<SourceRecord>>(`/sources${query({space_id:spaceId,cursor,limit:50})}`,signal));
 return <><div className="section-toolbar"><Input.Search placeholder="筛选本页数据来源" aria-label="筛选来源" value={filter} onChange={e=>setFilter(e.target.value)}/><Space><RefreshButton onClick={()=>{setSelected(undefined);sources.refresh();}}/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setEditing('new')}>添加来源</Button></Space></div><ResourceView resource={sources}>{data=><><List className="panel" dataSource={data.items.filter(s=>s.name.toLowerCase().includes(filter.toLowerCase()))} locale={{emptyText:'暂无数据来源。添加来源后，先预览原始快照，再启动同步。'}} renderItem={source=><List.Item actions={[<Button key="detail" onClick={()=>setSelected(source)}>预览与同步</Button>,<Button key="edit" disabled={source.state==='deleted'} onClick={()=>setEditing(source)}>更新配置</Button>]}><List.Item.Meta avatar={<FileOutlined className="list-icon"/>} title={<Space>{source.name}<Tag>{source.kind}</Tag><Tag>v{source.version}</Tag>{source.state==='deleted'&&<Tag>已删除</Tag>}</Space>} description={<><div>{source.config.url??source.config.path}</div><span>{source.preview?`${source.preview.file_count} 个文件 · 已固定原始版本`:'尚未预览'} · {formatDate(source.updated_at)}</span></>}/></List.Item>}/><div className="pagination"><Button disabled={!cursor} onClick={()=>setCursor(undefined)}>第一页</Button><Button disabled={!data.next_cursor} onClick={()=>setCursor(data.next_cursor??undefined)}>下一页</Button></div></>}</ResourceView>{editing&&<SourceForm spaceId={spaceId} source={editing==='new'?undefined:editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);sources.refresh();}}/>}<Drawer width={900} title={selected?.name??'数据来源'} open={!!selected} onClose={()=>setSelected(undefined)} destroyOnHidden>{selected&&<SourceActions key={`${selected.id}:${selected.version}`} source={selected} onChanged={sources.refresh} onManageACL={onManageACL}/>}</Drawer></>;
}
interface SourceFields {name:string;kind:SourceRecord['kind'];url?:string;ref?:string;path?:string;content?:string;username?:string;password?:string;ssh_private_key?:string;ssh_known_hosts?:string;clearCredential?:boolean}
export function SourceForm({spaceId,source,onClose,onSaved}:{spaceId:string;source?:SourceRecord;onClose:()=>void;onSaved:()=>void}){
 const {api}=useAuth();const [form]=Form.useForm<SourceFields>();const kind=Form.useWatch('kind',form)??source?.kind??'git';const mutation=useMutation();
 const clearSecrets=()=>{for(const key of ['username','password','ssh_private_key','ssh_known_hosts'])form.setFieldValue(key,'');};
 const submit=(values:SourceFields)=>{const credential=Object.fromEntries(['username','password','ssh_private_key','ssh_known_hosts'].flatMap(key=>values[key as keyof SourceFields]?[[key,values[key as keyof SourceFields]]]:[]));clearSecrets();const config=values.kind==='git'?{url:values.url,ref:values.ref}:{path:values.path,content:values.content};const secretField=values.clearCredential?{credential:null}:Object.keys(credential).length?{credential}:{};void mutation.run(()=>source?api.patch(`/sources/${pathId(source.id)}`,{base_version:source.version,name:values.name,config,...secretField}):api.post('/sources',{name:values.name,space_id:spaceId,kind:values.kind,config,...secretField}),onSaved);};
 return <Modal open width={820} title={source?'更新来源配置':'添加数据来源'} footer={null} onCancel={()=>{clearSecrets();onClose();}} destroyOnHidden><Form form={form} layout="vertical" onFinish={submit} initialValues={{name:source?.name??'',kind:source?.kind??'git',url:source?.config.url??'',ref:source?.config.ref??'refs/heads/main',path:source?.config.path??'',content:'',clearCredential:false}}><div className="form-grid"><Form.Item label="来源名称" name="name" rules={[{required:true,whitespace:true,message:'请输入来源名称'}]}><Input maxLength={200}/></Form.Item><Form.Item label="来源类型" name="kind"><Select disabled={!!source} options={[{value:'git',label:'Git 仓库'},{value:'markdown',label:'Markdown 文档'},{value:'ticket',label:'JSON 工单'}]}/></Form.Item></div>{kind==='git'?<><Form.Item name="url" label="仓库 URL" rules={[{required:true,message:'请输入 HTTPS 或 SSH 仓库 URL'}]}><Input placeholder="https://git.example/team/repo.git" autoComplete="off"/></Form.Item><Form.Item name="ref" label="分支 / 标签 / 提交引用" rules={[{required:true,message:'请指定引用'}]}><Input placeholder="refs/heads/main"/></Form.Item><Collapse items={[{key:'credential',forceRender:true,label:source?.has_credential?'访问凭据（已配置，留空保留）':'私有仓库访问凭据',children:<><Typography.Paragraph type="secondary">凭据仅写入服务端，提交后输入清空。SSH 必须同时提供用户名、私钥与已验证的 known_hosts。</Typography.Paragraph><div className="form-grid"><Form.Item name="username" label="用户名"><Input autoComplete="off"/></Form.Item><Form.Item name="password" label="访问令牌 / 密码"><Input.Password visibilityToggle={false} autoComplete="new-password"/></Form.Item></div><Form.Item name="ssh_private_key" label="SSH 私钥"><Input.Password visibilityToggle={false} autoComplete="new-password"/></Form.Item><Form.Item name="ssh_known_hosts" label="SSH known_hosts"><Input.TextArea autoSize={{minRows:2,maxRows:4}} autoComplete="off"/></Form.Item>{source?.has_credential&&<Form.Item name="clearCredential" label="清除已有访问凭据" valuePropName="checked"><Switch/></Form.Item>}</>}]}/></>:<><Form.Item label="相对文件路径" name="path" rules={[{required:true,message:'请输入相对路径'}]}><Input placeholder={kind==='markdown'?'docs/guide.md':'tickets/INC-1.json'}/></Form.Item>{source&&<Alert type="info" message="已保存的上传正文不通过配置接口返回。更新时请提供该版本完整原文。"/>}<Form.Item name="content" label={kind==='markdown'?'Markdown 原文':'JSON 工单原文'} rules={[{required:true,message:'请提供完整原文'}]}><Input.TextArea className="editor-textarea" autoSize={{minRows:10,maxRows:20}}/></Form.Item><Typography.Paragraph type="secondary">原始文件最大 4,000,000 字节。JSON 工单按提供的原文保留，不自动重写内容。</Typography.Paragraph></>}<ErrorNotice error={mutation.error}/><div className="form-footer"><Typography.Text type="secondary">保存配置后需先预览，再发起同步。</Typography.Text><Space><Button onClick={()=>{clearSecrets();onClose();}}>取消</Button><Button type="primary" htmlType="submit" loading={mutation.busy}>{source?'保存新版本':'添加来源'}</Button></Space></div></Form></Modal>;
}
export function SourceActions({source,onChanged,onManageACL}:{source:SourceRecord;onChanged:()=>void;onManageACL?:()=>void}){
 const {api}=useAuth();const [preview,setPreview]=useState<SourcePreview>(),[task,setTask]=useState<IngestTask>(),[taskId,setTaskId]=useState<string>();const mutation=useMutation();const deleted=source.state==='deleted';
 return <><Descriptions column={1} size="small" items={[{key:'kind',label:'来源类型',children:source.kind},{key:'version',label:'配置版本',children:`v${source.version}`},{key:'resource',label:'权限资源',children:source.resource_id},{key:'credential',label:'访问凭据',children:source.has_credential?'已配置（不可读取）':'未配置'},{key:'preview',label:'固定版本',children:preview?.source_revision??source.preview?.source_revision??'尚未预览'}]}/><div className="section-toolbar"><Space wrap><Button icon={<EyeOutlined/>} disabled={deleted} loading={mutation.busy} onClick={()=>void mutation.run(()=>api.post<SourcePreview>(`/sources/${pathId(source.id)}/preview`,{base_version:source.version}),result=>{setPreview(result);onChanged();})}>预览原始快照</Button><Button type="primary" icon={<CloudSyncOutlined/>} disabled={deleted||(!preview&&!source.preview)} loading={mutation.busy} onClick={()=>void mutation.run(()=>api.post<IngestTask>(`/sources/${pathId(source.id)}/sync`,{base_version:source.version}),result=>{setTask(result);onChanged();})}>启动同步</Button><Popconfirm title="删除此数据来源？" description="保留原始快照与审计，并创建移除审核提案；已排队的旧任务会被阻止发布。" onConfirm={()=>mutation.run(()=>api.delete<IngestTask>(`/sources/${pathId(source.id)}`,{base_version:source.version}),result=>{setTask(result);onChanged();})}><Button danger disabled={deleted}>删除来源</Button></Popconfirm></Space></div><ErrorNotice error={mutation.error}/>{mutation.error instanceof ApiError&&mutation.error.code==='worker_authorization_required'&&<Alert type="warning" showIcon message="接入 worker 尚未获得知识权限" description={<span>空间负责人需为已登记的 worker 服务账号配置空间及来源资源的读取、编辑授权。{onManageACL?<Button type="link" onClick={onManageACL}>打开空间授权</Button>:<Link to={`/spaces/${pathId(source.space_id)}?tab=settings`}>打开空间授权</Link>}</span>}/>}<Alert type="info" message="预览只固定原始快照，不发布知识。同步会返回持久任务，完成状态由 worker 实际执行结果决定。"/>{task&&<div className="task-notice"><Tag color="blue">{taskLabels[task.status]}</Tag><span>已受理任务 {task.id} </span><Button size="small" onClick={()=>setTaskId(task.id)}>查看任务</Button></div>}{preview&&<><Typography.Title level={4}>预览文件 · {preview.file_count} 个 / {preview.total_bytes.toLocaleString()} 字节</Typography.Title>{preview.diagnostics.map((message,index)=><Alert key={index} type="warning" message={message}/>)}<List dataSource={preview.files} renderItem={file=><List.Item><List.Item.Meta title={<Space><Tag>{file.kind}</Tag>{file.path}</Space>} description={<><div>{file.size.toLocaleString()} 字节 · <span className="hash">{file.sha256}</span></div>{file.diagnostics.map((item,index)=><div key={index}>{item}</div>)}</>}/></List.Item>}/></>}<Typography.Title level={4}>此来源任务</Typography.Title><TasksPanel spaceId={source.space_id} sourceId={source.id}/><Drawer width={720} open={!!taskId} title="同步任务" onClose={()=>setTaskId(undefined)} destroyOnHidden>{taskId&&<TaskDetail id={taskId}/>}</Drawer></>;
}
export function TasksPanel({spaceId,sourceId}:{spaceId?:string;sourceId?:string}){const {api}=useAuth();const [cursor,setCursor]=useState<string>(),[selected,setSelected]=useState<string>();const tasks=useResource(`tasks:${spaceId}:${sourceId}:${cursor}`,signal=>api.get<ListResult<IngestTask>>(`/tasks${query({space_id:spaceId,source_id:sourceId,cursor,limit:50})}`,signal));return <><div className="section-toolbar"><Typography.Text type="secondary">实际任务状态 · 刷新以重新检查权限与进度</Typography.Text><RefreshButton onClick={()=>{setSelected(undefined);tasks.refresh();}}/></div><ResourceView resource={tasks}>{data=><><List className="panel" dataSource={data.items} locale={{emptyText:'暂无可读取的接入任务'}} renderItem={task=><List.Item actions={[<Button key="detail" onClick={()=>setSelected(task.id)}>查看详情</Button>]}><List.Item.Meta title={<Space><Tag color={task.status==='failed'?'red':task.status==='succeeded'?'green':'blue'}>{taskLabels[task.status]??task.status}</Tag>{task.operation==='sync'?'同步来源':'删除来源'} · v{task.source_version}</Space>} description={<>{task.source_id}<div>{formatDate(task.updated_at)} · {task.stage}</div>{task.error_code&&<Typography.Text type="danger">{task.error_code}</Typography.Text>}</>}/></List.Item>}/><div className="pagination"><Button disabled={!cursor} onClick={()=>setCursor(undefined)}>第一页</Button><Button disabled={!data.next_cursor} onClick={()=>setCursor(data.next_cursor??undefined)}>下一页</Button></div></>}</ResourceView><Drawer open={!!selected} width={800} title="任务详情" onClose={()=>setSelected(undefined)} destroyOnHidden>{selected&&<TaskDetail id={selected}/>}</Drawer></>;}
function TaskDetail({id}:{id:string}){const {api}=useAuth();const task=useResource(`task:${id}`,signal=>api.get<IngestTask>(`/tasks/${pathId(id)}`,signal));return <><RefreshButton onClick={task.refresh}/><ResourceView resource={task}>{value=><><Typography.Title level={4}>{taskLabels[value.status]??value.status}</Typography.Title><Descriptions column={1} items={[{key:'id',label:'任务 ID',children:value.id},{key:'source',label:'来源 / 版本',children:`${value.source_id} / v${value.source_version}`},{key:'stage',label:'当前阶段',children:value.stage},{key:'created',label:'创建时间',children:formatDate(value.created_at)},{key:'updated',label:'更新时间',children:formatDate(value.updated_at)}]}/>{value.error_code&&<Alert type="error" message={`任务错误：${value.error_code}`}/>}<Tabs items={[{key:'result',label:'实际处理结果',children:<pre className="audit-detail">{JSON.stringify(value.result,null,2)}</pre>} ]}/>{value.status==='review_needed'&&<Link to="/reviews">前往知识审核</Link>}</>}</ResourceView></>;}