import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Alert, Button, Card, Empty, Form, Input, List, Modal, Select, Space as Inline, Tabs, Tag, Typography } from 'antd';
import { ArrowLeftOutlined, ArrowRightOutlined, FileTextOutlined, FolderOutlined, PlusOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { useAuth } from '../auth';
import { pathId, query } from '../api';
import { useMutation, useResource } from '../hooks';
import type { Action, Grant, ListResult, Principal, Space, WikiPage } from '../types';
import { ErrorNotice, PageHeader, RefreshButton, ResourceView, StatusTag } from '../components/Common';
import { PageEditor } from './Wiki';
import { ServiceRecords } from './Experience';
import { SourcesPanel } from './Sources';
import { GraphExplorer } from './GraphExplorer';
export function SpacesPage({principal}:{principal:Principal}){const {api}=useAuth();const spaces=useResource('spaces',signal=>api.get<ListResult<Space>>('/spaces',signal));const [open,setOpen]=useState(false),[filter,setFilter]=useState('');const mutation=useMutation();const [form]=Form.useForm<{name:string}>();return <><PageHeader eyebrow="KNOWLEDGE SPACES" title="知识空间" description="将团队知识组织在清晰的边界中。这里只展示你当前可读取的空间。" extra={<Inline><RefreshButton onClick={spaces.refresh}/>{principal.permissions.includes('platform_admin')&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>新建空间</Button>}</Inline>}/><Input.Search className="filter-input" placeholder="筛选已加载的空间" aria-label="筛选知识空间" value={filter} onChange={e=>setFilter(e.target.value)}/><ResourceView resource={spaces}>{data=>data.items.length?<div className="space-grid">{data.items.filter(s=>s.name.toLowerCase().includes(filter.toLowerCase())).map(space=><Link to={`/spaces/${pathId(space.id)}`} key={space.id} className="space-card-link"><Card className="space-card" hoverable><div className="space-card-icon"><FolderOutlined/></div><Typography.Title level={4}>{space.name}</Typography.Title><Typography.Paragraph type="secondary">Wiki · 来源 · 版本与权限</Typography.Paragraph><div className="card-footer"><span><SafetyCertificateOutlined/> 实时授权</span><ArrowRightOutlined/></div></Card></Link>)}</div>:<Empty description="暂无可读取的知识空间。创建空间，或请空间负责人授予访问权限。"/>}</ResourceView><Modal title="新建知识空间" open={open} onCancel={()=>{setOpen(false);form.resetFields();mutation.clearError();}} footer={null} destroyOnHidden><Form form={form} layout="vertical" onFinish={values=>void mutation.run(()=>api.post<Space>('/spaces',values),()=>{setOpen(false);form.resetFields();spaces.refresh();})}><Form.Item name="name" label="空间名称" rules={[{required:true,whitespace:true,message:'请输入空间名称'}]}><Input maxLength={200} placeholder="例如：研发平台"/></Form.Item><Alert type="info" showIcon message="创建后，你将获得此空间的读取、编辑、授权与审核权限。"/><ErrorNotice error={mutation.error}/><Button className="form-submit" htmlType="submit" type="primary" loading={mutation.busy}>创建空间</Button></Form></Modal></>;}
export function SpaceDetail(){const {spaceId=''}=useParams();const {api}=useAuth();const space=useResource(`space:${spaceId}`,signal=>api.get<Space>(`/spaces/${pathId(spaceId)}`,signal));return <><Link className="back-link" to="/spaces"><ArrowLeftOutlined/> 全部空间</Link><ResourceView resource={space}>{value=><><PageHeader title={value.name} description="源文件是证据，Wiki 是正式知识；每次修改都保留版本与审核记录。"/><Tabs defaultActiveKey="wiki" destroyOnHidden items={[{key:'wiki',label:'Wiki',children:<WikiList key={spaceId} spaceId={spaceId}/>},{key:'sources',label:'数据来源',children:<SourcesPanel spaceId={spaceId} onManageACL={()=>{}}/>},{key:'graph',label:'知识图谱',children:<GraphExplorer spaceId={spaceId}/>},{key:'activity',label:'活动',children:<ServiceRecords path={`/tasks${query({space_id:spaceId})}`} title="暂无同步任务" description="真实来源任务会显示在这里；审核记录可在「任务与审核」查看。"/>},{key:'settings',label:'空间设置',children:<GrantEditor key={spaceId} spaceId={spaceId}/>} ]}/></>}</ResourceView></>;}
function WikiList({spaceId}:{spaceId:string}){const {api}=useAuth();const [cursor,setCursor]=useState<string>(),[filter,setFilter]=useState(''),[create,setCreate]=useState(false);const pages=useResource(`pages:${spaceId}:${cursor}`,signal=>api.get<ListResult<WikiPage>>(`/pages${query({space_id:spaceId,cursor,limit:50})}`,signal));return <><div className="section-toolbar"><Input.Search placeholder="筛选本页 Wiki" aria-label="筛选 Wiki" value={filter} onChange={e=>setFilter(e.target.value)}/><Inline><RefreshButton onClick={pages.refresh}/><Button icon={<PlusOutlined/>} type="primary" onClick={()=>setCreate(true)}>撰写页面</Button></Inline></div><ResourceView resource={pages}>{data=><><List className="panel wiki-list" locale={{emptyText:'还没有已发布的 Wiki。创建草稿并提交审核，或接入代码来源。'}} dataSource={data.items.filter(page=>page.revision?.content.title.toLowerCase().includes(filter.toLowerCase()))} renderItem={page=><List.Item extra={<Tag>v{page.revision_number}</Tag>}><List.Item.Meta avatar={<FileTextOutlined className="list-icon"/>} title={<Link to={`/spaces/${pathId(spaceId)}/pages/${pathId(page.id)}`}>{page.revision?.content.title??page.id}</Link>} description={<Inline><StatusTag status={page.revision?.content.state??'pending'}/>{page.revision?.content.entity_type??'知识页面'}</Inline>}/></List.Item>}/><div className="pagination"><Button disabled={!cursor} onClick={()=>setCursor(undefined)}>回到第一页</Button><Button disabled={!data.next_cursor} onClick={()=>setCursor(data.next_cursor??undefined)}>下一页</Button></div></>}</ResourceView><PageEditor open={create} spaceId={spaceId} onClose={()=>setCreate(false)} onSaved={()=>{setCreate(false);pages.refresh();}}/></>;}
export function GrantEditor({spaceId}:{spaceId:string}){const {api}=useAuth();const [resourceInput,setResourceInput]=useState(''),[resourceId,setResourceId]=useState('');const grants=useResource(`grants:${spaceId}:${resourceId}`,signal=>api.get<ListResult<Grant>>(`/grants${query({space_id:spaceId,resource_id:resourceId})}`,signal));return <div className="narrow-panel"><Typography.Title level={4}>空间与资源授权</Typography.Title><Alert type="info" showIcon message="有效权限 = 空间权限 ∩ 资源权限" description="管理权限不会自动授予内容读取权。资源授权只能收紧空间权限；清空主体会拒绝全部访问。"/><div className="section-toolbar"><Input value={resourceInput} onChange={e=>setResourceInput(e.target.value)} placeholder="资源 ID（留空管理空间授权）" aria-label="资源 ID"/><Button onClick={()=>setResourceId(resourceInput.trim())}>读取授权</Button></div><ResourceView resource={grants}>{data=><GrantForm key={`${spaceId}:${resourceId}:${JSON.stringify(data.items)}`} spaceId={spaceId} resourceId={resourceId} grants={data.items} onSaved={grants.refresh}/>}</ResourceView></div>;}
function GrantForm({spaceId,resourceId,grants,onSaved}:{spaceId:string;resourceId:string;grants:Grant[];onSaved:()=>void}){const {api}=useAuth();const [action,setAction]=useState<Action>('read');const current=grants.find(grant=>grant.action===action);const [form]=Form.useForm();const mutation=useMutation();return <><Select aria-label="授权操作" value={action} onChange={value=>{setAction(value);form.resetFields();mutation.clearError();}} options={[{value:'read',label:'读取'},{value:'write',label:'编辑'},{value:'grant',label:'授权管理'},{value:'review',label:'审核'}]}/><Form key={action} form={form} layout="vertical" initialValues={{subjects:current?.subjects?.join('\n')??'',mode:resourceId&&current?.subjects===null?'inherit':'explicit'}} onFinish={values=>void mutation.run(()=>api.put('/grants',{space_id:spaceId,...(resourceId?{resource_id:resourceId}:{}),action,subjects:values.mode==='inherit'?null:String(values.subjects??'').split(/[\n,]/).map(v=>v.trim()).filter(Boolean)}),onSaved)}><Form.Item name="mode" label="授权方式"><Select options={[{value:'explicit',label:'指定主体'},...(resourceId?[{value:'inherit',label:'继承空间权限'}]:[])]}/></Form.Item><Form.Item name="subjects" label="授权主体（每行一个）" extra="使用 user:ID、service:ID、group:ID 或 department:ID。ID 必须已在组织中登记。"><Input.TextArea autoSize={{minRows:5,maxRows:12}} placeholder="user:已登记的主体 ID"/></Form.Item><ErrorNotice error={mutation.error}/><Button htmlType="submit" type="primary" loading={mutation.busy}>保存授权</Button></Form></>;}