import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Button, Collapse, Descriptions, Drawer, Empty, Form, Input, List, Modal, Select, Space, Tabs, Typography } from 'antd';
import { ArrowLeftOutlined, EditOutlined, HistoryOutlined, RollbackOutlined } from '@ant-design/icons';
import { useAuth } from '../auth';
import { ApiError, pathId, query } from '../api';
import { useMutation, useResource } from '../hooks';
import type { EvidenceRef, ListResult, PageContent, Proposal, Revision, WikiPage } from '../types';
import { entityTypes } from '../types';
import { ContentDiff, SafeMarkdown } from '../components/Content';
import { CitationDrawer, EvidenceList } from '../components/Citation';
import { ErrorNotice, formatDate, PageHeader, RefreshButton, ResourceView, StatusTag } from '../components/Common';
export function allEvidence(content:PageContent):EvidenceRef[]{const seen=new Set<string>();return [...content.evidence,...content.claims.flatMap(claim=>claim.evidence)].filter(ref=>{const key=JSON.stringify(ref);if(seen.has(key))return false;seen.add(key);return true;});}
export function WikiPageDetail(){const {pageId=''}=useParams();const {api}=useAuth();const page=useResource(`page:${pageId}`,signal=>api.get<WikiPage>(`/pages/${pathId(pageId)}`,signal));const [editing,setEditing]=useState(false),[history,setHistory]=useState(false),[citation,setCitation]=useState<EvidenceRef|null>(null);return <ResourceView resource={page}>{value=><><Link className="back-link" to={`/spaces/${pathId(value.space_id)}`}><ArrowLeftOutlined/> 返回空间</Link><PageHeader eyebrow="VERSIONED WIKI" title={value.revision?.content.title??'待发布草稿'} description={value.revision?`版本 ${value.revision_number} · ${formatDate(value.revision.created_at)}`:'草稿尚未成为正式知识，请在任务与审核中审阅。'} extra={<Space><RefreshButton onClick={page.refresh}/><Button icon={<HistoryOutlined/>} onClick={()=>setHistory(true)}>历史版本</Button><Button type="primary" icon={<EditOutlined/>} onClick={()=>setEditing(true)}>提出修改</Button></Space>}/>{value.revision?<div className="wiki-layout"><div className="panel wiki-content"><Space><StatusTag status={value.revision.content.state}/>{value.revision.content.entity_type&&<Typography.Text type="secondary">{value.revision.content.entity_type}</Typography.Text>}</Space><SafeMarkdown text={value.revision.content.markdown}/>{value.revision.content.claims.length>0&&<><Typography.Title level={4}>结构化声明</Typography.Title><List dataSource={value.revision.content.claims} renderItem={claim=><List.Item><div><Space><StatusTag status={claim.state}/><Typography.Text type="secondary">{{fact:'事实',inference:'推断',gap:'知识缺口'}[claim.kind]}</Typography.Text></Space><p>{claim.text}</p><EvidenceList evidence={claim.evidence} onSelect={setCitation}/></div></List.Item>}/></>}</div><aside className="panel wiki-aside"><Typography.Title level={5}>证据来源</Typography.Title>{allEvidence(value.revision.content).length?<EvidenceList evidence={allEvidence(value.revision.content)} onSelect={setCitation}/>:<Typography.Paragraph type="secondary">此页面没有结构化原文引用。审核叙述不自动视为新增独立证据。</Typography.Paragraph>}<div className="aside-separator"/><Typography.Title level={5}>版本信息</Typography.Title><div className="hash">{value.current_revision}</div><Typography.Paragraph type="secondary">作者：{value.revision.created_by}<br/>发布方式：{value.revision.publication_kind}</Typography.Paragraph></aside></div>:<Empty description={<span>页面尚未发布。<Link to="/reviews">前往审核</Link></span>}/>}<PageEditor open={editing} page={value} spaceId={value.space_id} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);page.refresh();}}/><RevisionHistory open={history} page={value} onClose={()=>setHistory(false)} onPublished={()=>{setHistory(false);page.refresh();}}/><CitationDrawer evidence={citation} onClose={()=>setCitation(null)}/></>}</ResourceView>;}
interface PageEditorProps {open:boolean;spaceId:string;page?:WikiPage;onClose:()=>void;onSaved:()=>void}
export function PageEditor(props:PageEditorProps){return props.open?<EditorForm {...props}/>:null;}
interface EditFields {title:string;markdown:string;entity_type:PageContent['entity_type'];reason:string;evidenceJson:string;claimsJson:string}
function EditorForm({spaceId,page,onClose,onSaved}:PageEditorProps){const {api}=useAuth();const navigate=useNavigate();const [base,setBase]=useState(page?.current_revision??null);const [latest,setLatest]=useState<WikiPage>();const [proposed,setProposed]=useState<PageContent>();const [parseError,setParseError]=useState<string>();const [form]=Form.useForm<EditFields>();const mutation=useMutation();const content=page?.revision?.content;const initial:EditFields={title:content?.title??'',markdown:content?.markdown??'',entity_type:content?.entity_type??null,reason:'',evidenceJson:JSON.stringify(content?.evidence??[],null,2),claimsJson:JSON.stringify(content?.claims??[],null,2)};
  const submit=(values:EditFields)=>{setParseError(undefined);let evidence:EvidenceRef[],claims:PageContent['claims'];try{evidence=JSON.parse(values.evidenceJson);claims=JSON.parse(values.claimsJson);if(!Array.isArray(evidence)||!Array.isArray(claims))throw new Error();}catch{setParseError('证据与声明必须是有效的 JSON 数组。');return;}const next:PageContent={...(content??{state:'valid' as const}),title:values.title,markdown:values.markdown,entity_type:values.entity_type??null,evidence,claims};setProposed(next);void mutation.run(()=>page?api.post<Proposal>(`/pages/${pathId(page.id)}/proposals`,{base_revision:base,content:next,kind:'formal_change',reason:values.reason}):api.post<{page:WikiPage;proposal:Proposal}>('/pages',{space_id:spaceId,content:next,reason:values.reason}),result=>{onSaved();if(!page&&'page' in result)navigate(`/spaces/${pathId(spaceId)}/pages/${pathId(result.page.id)}`);});};
  return <Modal open width={960} title={page?'提出 Wiki 修改':'撰写 Wiki 草稿'} onCancel={onClose} footer={null} maskClosable={!mutation.busy} destroyOnHidden><Alert type="info" showIcon message="提交后进入人工审核，批准后生成新的不可变版本。"/><Form form={form} layout="vertical" initialValues={initial} onFinish={submit}><div className="form-grid"><Form.Item label="页面标题" name="title" rules={[{required:true,whitespace:true,message:'请输入页面标题'}]}><Input maxLength={512}/></Form.Item><Form.Item label="实体类型" name="entity_type"><Select allowClear options={entityTypes.map(value=>({value,label:value}))}/></Form.Item></div><Form.Item label="正文（Markdown）" name="markdown" rules={[{required:true,message:'请输入正文'}]}><Input.TextArea className="editor-textarea" autoSize={{minRows:12,maxRows:22}}/></Form.Item><Collapse items={[{key:'evidence',label:'高级：原始证据与结构化声明',children:<><Typography.Paragraph type="secondary">证据必须指向已登记的不可变原始快照。正式事实声明需要原始证据；摘要不能作为新增独立证据。</Typography.Paragraph><Form.Item name="evidenceJson" label="EvidenceRef 数组"><Input.TextArea className="editor-textarea" autoSize={{minRows:4,maxRows:12}}/></Form.Item><Form.Item name="claimsJson" label="Claim 数组"><Input.TextArea className="editor-textarea" autoSize={{minRows:4,maxRows:12}}/></Form.Item></>}]}/><Form.Item label="修改理由" name="reason" rules={[{required:true,whitespace:true,message:'请说明修改理由'}]}><Input.TextArea maxLength={4096} placeholder="说明变更依据与需要审核的结论"/></Form.Item>{parseError&&<Alert type="error" message={parseError}/>}<ErrorNotice error={mutation.error}/>{mutation.error instanceof ApiError&&mutation.error.status===409&&page&&<Button onClick={()=>void mutation.run(()=>api.get<WikiPage>(`/pages/${pathId(page.id)}`),setLatest)}>读取最新版本并比较</Button>}{latest&&<><Alert type="warning" message="请核对最新内容后再决定是否重新提交。当前编辑内容不会自动合并。"/><ContentDiff before={latest.revision?.content.markdown??''} after={proposed?.markdown??form.getFieldValue('markdown')}/><Button onClick={()=>{setBase(latest.current_revision);setLatest(undefined);mutation.clearError();}}>已核对，改用最新版本作为基准</Button></>}<div className="form-footer"><Typography.Text type="secondary">基准版本：{base??'首次发布'}</Typography.Text><Space><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={mutation.busy}>提交审核</Button></Space></div></Form></Modal>;
}
function RevisionHistory({open,page,onClose,onPublished}:{open:boolean;page:WikiPage;onClose:()=>void;onPublished:()=>void}){return <Drawer width={900} title="历史版本与回退" open={open} onClose={onClose} destroyOnHidden>{open&&<HistoryBody page={page} onPublished={onPublished}/>}</Drawer>;}
function HistoryBody({page,onPublished}:{page:WikiPage;onPublished:()=>void}){const {api}=useAuth();const [cursor,setCursor]=useState<string>(),[selected,setSelected]=useState<Revision>(),[reason,setReason]=useState(''),[rollback,setRollback]=useState(false);const versions=useResource(`versions:${page.id}:${cursor}`,signal=>api.get<ListResult<Revision>>(`/pages/${pathId(page.id)}/revisions${query({cursor,limit:50})}`,signal));const mutation=useMutation();return <><ResourceView resource={versions}>{data=><><List dataSource={data.items} locale={{emptyText:'尚无已发布版本'}} renderItem={revision=><List.Item actions={[<Button key="view" onClick={()=>setSelected(revision)}>查看差异</Button>]}><List.Item.Meta title={<Space>版本 {revision.number}<StatusTag status={revision.content.state}/>{revision.id===page.current_revision&&<Typography.Text type="secondary">当前版本</Typography.Text>}</Space>} description={`${formatDate(revision.created_at)} · ${revision.created_by}`}/></List.Item>}/><Space><Button disabled={!cursor} onClick={()=>setCursor(undefined)}>第一页</Button><Button disabled={!data.next_cursor} onClick={()=>setCursor(data.next_cursor??undefined)}>更早版本</Button></Space></>}</ResourceView>{selected&&<><Typography.Title level={4}>版本 {selected.number}</Typography.Title><Descriptions size="small" column={1} items={[{key:'id',label:'不可变版本',children:selected.id},{key:'base',label:'父版本',children:selected.base_revision??'无'}]}/><Tabs items={[{key:'read',label:'正文',children:<SafeMarkdown text={selected.content.markdown}/>},{key:'diff',label:'与当前正文比较',children:<ContentDiff before={page.revision?.content.markdown??''} after={selected.content.markdown}/>},{key:'structured',label:'完整内容差异',children:<ContentDiff before={JSON.stringify(page.revision?.content??{},null,2)} after={JSON.stringify(selected.content,null,2)}/>} ]}/>{selected.id!==page.current_revision&&page.current_revision&&<Button icon={<RollbackOutlined/>} onClick={()=>setRollback(true)}>将此内容发布为新版本</Button>}<Modal title={`回退到版本 ${selected.number} 的内容`} open={rollback} onCancel={()=>setRollback(false)} onOk={()=>void mutation.run(()=>api.post(`/pages/${pathId(page.id)}/rollback`,{base_revision:page.current_revision,revision_id:selected.id,reason}),onPublished)} okButtonProps={{disabled:!reason.trim()}} confirmLoading={mutation.busy} okText="发布新版本"><Alert type="info" message="历史记录保持不变；回退会新建一个版本，且需要当前审核权限。"/><Input.TextArea aria-label="回退理由" placeholder="填写回退理由" value={reason} onChange={e=>setReason(e.target.value)} maxLength={4096}/><ErrorNotice error={mutation.error}/></Modal></>}</>;}