import { ConfigProvider } from "antd";
import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { ChatPage } from "../pages/Chat";
import { AgentsPage } from "../pages/Agents";
const {api}=vi.hoisted(()=>({api:{get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}}));
vi.mock("../auth",()=>({useAuth:()=>({api})}));
vi.mock("../components/AgentRun",()=>({RunPanel:({runId}:{runId:string})=><div>真实运行 {runId}</div>}));
const config={mode:"knowledge_qa",model_configuration_id:"model-v",prompt:"",space_ids:["space"],tools:["search","get"],tool_space_ids:{},budget:{model_rounds:8,tool_calls:20,parallel_reads:2,seconds:180},max_output_tokens:2048};
const agent={id:"agent",configuration_id:"config-v",version:2,name:"研发问答",description:"",owner_space_id:"space",created_by:"user",shared:true,published_configuration_id:"config-v",config,created_at:"2026-09-08T00:00:00Z"};
beforeEach(()=>{vi.clearAllMocks();api.get.mockImplementation(async(path:string)=>{if(path.startsWith("/spaces"))return {items:[{id:"space",name:"研发知识"}]};if(path.startsWith("/agents/presets"))return {items:[{id:"knowledge_qa",name:"知识问答",instruction:"检索引用",tools:["search","get"],model_configuration_id:null}]};if(path.startsWith("/agents/models"))return {items:[{id:"model",configuration_id:"model-v",name:"Qwen",provider_model:"qwen-plus",test_state:"passed",capability:"chat",state:"active",capabilities:{}}]};if(path.startsWith("/agents/agent/versions"))return {items:[agent]};if(path.startsWith("/agents/agent"))return agent;if(path.startsWith("/agents"))return {items:[agent]};if(path.includes("/history"))return {items:[]};if(path.startsWith("/sessions"))return {items:[{id:"session",title:"追溯会话",created_at:"2026-09-08T00:00:00Z"}]};throw new Error(path)});});
function mount(page:"chat"|"agents",url=page==="chat"?"/chat":"/agents"){render(<ConfigProvider theme={{token:{motion:false}}}><MemoryRouter initialEntries={[url]}>{page==="chat"?<ChatPage/>:<AgentsPage/>}</MemoryRouter></ConfigProvider>)}
describe("Agent pages",()=>{
 it("restores a run from the URL without creating another run",async()=>{mount("chat","/chat?session=session&run=restored");expect(await screen.findByText("真实运行 restored")).toBeInTheDocument();expect(api.post).not.toHaveBeenCalled()});
 it("submits selected agent configuration, session and intersection scope",async()=>{api.post.mockResolvedValue({id:"new-run",session_id:"session",event_seq:1,status:"queued",created_at:"2026-09-08T00:00:00Z",finished_at:null,content_hidden:false,agent_id:"agent",configuration_id:"config-v",actual_scope:["space"],question:"哪个服务依赖缓存？",answer:null,citations:[],usage:{},error_code:null,budget:config.budget,rounds:0,tool_calls:0});mount("chat","/chat?session=session&agent=agent");await screen.findByText("研发问答");fireEvent.change(screen.getByRole("textbox",{name:"问题"}),{target:{value:"哪个服务依赖缓存？"}});fireEvent.click(screen.getByRole("button",{name:"发送问题"}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/runs",expect.objectContaining({agent_id:"agent",configuration_id:"config-v",session_id:"session",space_ids:["space"],question:"哪个服务依赖缓存？"})));expect(await screen.findByText("真实运行 new-run")).toBeInTheDocument()});
 it("offers actual setup guidance when there are no agents",async()=>{api.get.mockImplementation(async(path:string)=>path.startsWith("/spaces")?{items:[{id:"space",name:"研发知识"}]}:{items:[]});mount("chat");expect(await screen.findByRole("link",{name:"创建智能体"})).toHaveAttribute("href","/agents");expect(screen.getByRole("button",{name:"发送问题"})).toBeDisabled()});
 it("publishes with the exact reviewed configuration CAS",async()=>{api.post.mockResolvedValue({id:"agent",configuration_id:"config-v",published_configuration_id:"config-v",shared:true});mount("agents");await screen.findByText("研发问答");fireEvent.click(screen.getByRole("button",{name:"配置与发布 研发问答"}));await screen.findByRole("button",{name:"发布当前版本"});fireEvent.click(screen.getByRole("button",{name:"发布当前版本"}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/agents/agent/publish",{base_configuration_id:"config-v",shared:true}))});
});
