import { ConfigProvider } from "antd";
import { act, fireEvent, render, renderHook, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiClient } from "../api";
import { decodeGraphResult } from "../graph-api";
import { useGraphExplorer } from "../graph-hooks";
import { useGraphSpace } from "../graph-space";
import { GRAPH_READ_DEADLINE_MS } from "../graph-deadline";
import { GraphEvidenceDrawer } from "../components/GraphEvidence";
import { graphResult, graphSnapshot } from "./graph-fixtures";
const params = { space_ids: ["space"], relation: { types: ["depends_on" as const], direction: "outgoing" as const, hops: 1 as const }, as_of: null, known_at: null, include_historical: false };
afterEach(() => vi.useRealTimers());
describe("finite graph read boundaries", () => {
  it("fences a hung passive request at its total deadline and ignores its uncancellable late response", async () => {
    vi.useFakeTimers();
    let late!: (value: unknown) => void;
    const request = vi.fn().mockResolvedValueOnce(graphResult()).mockImplementation(() => new Promise(resolve => { late = resolve; }));
    const api = { request } as unknown as ApiClient;
    const { result } = renderHook(() => useGraphExplorer(api));
    await act(async () => { await result.current.traverse(["fragment-a"], params); });
    await act(async () => { await vi.advanceTimersByTimeAsync(5000 + GRAPH_READ_DEADLINE_MS + 1); });
    expect(result.current.data).toBeUndefined();
    expect(result.current.error).toMatchObject({ code: "graph_read_timeout" });
    expect(request).toHaveBeenCalledTimes(2);
    expect(request.mock.calls[1][1].signal.aborted).toBe(true);
    await act(async () => { late(graphResult()); });
    expect(result.current.data).toBeUndefined();
    expect(result.current.loading).toBe(false);
  });
  it("keeps a normal slow space check coalesced but drops metadata once the same deadline expires", async () => {
    vi.useFakeTimers();
    let late!: (value: unknown) => void;
    const get = vi.fn().mockResolvedValueOnce({ id: "space", name: "PRIVATE-SPACE" }).mockImplementation(() => new Promise(resolve => { late = resolve; }));
    const api = { get } as unknown as ApiClient;
    const { result } = renderHook(() => useGraphSpace(api, "space"));
    await act(async () => {});
    await act(async () => { await vi.advanceTimersByTimeAsync(16000); });
    expect(get).toHaveBeenCalledTimes(2);
    expect(get.mock.calls[1][1].aborted).toBe(false);
    expect(result.current.data?.name).toBe("PRIVATE-SPACE");
    await act(async () => { await vi.advanceTimersByTimeAsync(20000); });
    expect(result.current.data).toBeUndefined();
    await act(async () => { late({ id: "space", name: "LATE-SPACE" }); });
    expect(result.current.data).toBeUndefined();
  });
  it("bounds the entire source sequence including the initial live check, not each phase independently", async () => {
    vi.useFakeTimers();
    const data = decodeGraphResult(graphResult());
    let late!: (value: unknown) => void;
    const get = vi.fn().mockImplementation(() => new Promise(resolve => { late = resolve; }));
    const api = { get } as unknown as ApiClient;
    const refresh = vi.fn().mockImplementation(() => new Promise(resolve => window.setTimeout(() => resolve(data), 20000)));
    const invalidate = vi.fn();
    render(<ConfigProvider theme={{ token: { motion: false } }}><MemoryRouter><GraphEvidenceDrawer api={api} data={data} selection={{ kind: "edge", id: "edge-ab" }} refresh={refresh} invalidate={invalidate} onClose={vi.fn()}/></MemoryRouter></ConfigProvider>);
    await act(async () => { fireEvent.click(screen.getByRole("button", { name: "查看原文 src/main.go" })); });
    await act(async () => { await vi.advanceTimersByTimeAsync(20000); });
    expect(get).toHaveBeenCalledTimes(1);
    expect(invalidate).not.toHaveBeenCalled();
    await act(async () => { await vi.advanceTimersByTimeAsync(10000); });
    expect(invalidate).toHaveBeenCalledWith(expect.objectContaining({ code: "graph_read_timeout" }));
    expect(get.mock.calls[0][1].aborted).toBe(true);
    await act(async () => { late(graphSnapshot); });
    expect(screen.queryByRole("region", { name: "原始引用逐行内容" })).not.toBeInTheDocument();
    expect(refresh).toHaveBeenCalledTimes(1);
  });
});