import { useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useParams, useSearchParams } from 'react-router-dom';
import { Alert, Avatar, Button, ConfigProvider, Layout, Menu, Result, Skeleton, Space, Tag, Typography } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { ApartmentOutlined, BookOutlined, CheckSquareOutlined, CommentOutlined, LogoutOutlined, MenuFoldOutlined, MenuUnfoldOutlined, RobotOutlined, SettingOutlined, SunOutlined } from '@ant-design/icons';
import { AuthProvider, useAuth } from './auth';
import { useResource } from './hooks';
import type { Principal } from './types';
import { ErrorNotice } from './components/Common';
import { CitationBody } from './components/Citation';
import { SpacesPage, SpaceDetail } from './pages/Spaces';
import { WikiPageDetail } from './pages/Wiki';
import { ReviewsPage } from './pages/Reviews';
import { SettingsPage } from './pages/Settings';
import { AgentsPage, ChatPage } from './pages/Experience';
export function App(){return <ConfigProvider locale={zhCN} theme={{token:{colorPrimary:'#2b766d',colorInfo:'#2b766d',colorBgLayout:'#f7f9fc',colorText:'#202b3c',borderRadius:10,fontFamily:'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", sans-serif'},components:{Button:{controlHeight:38},Menu:{itemSelectedBg:'#e9f2ef',itemSelectedColor:'#21685f'}}}}><AuthProvider><BrowserRouter><Gate/></BrowserRouter></AuthProvider></ConfigProvider>;}
function Gate(){const auth=useAuth();if(auth.loading)return <div className="login-page"><Skeleton active/></div>;if(!auth.user)return <div className="login-page"><div className="login-brand"><SunOutlined/> 晴知 <span>SUNNY KNOWLEDGE</span></div><div className="login-card"><Tag color="green">企业知识 · 有据可循</Tag><Typography.Title>让团队知识<br/>连接每一次决策。</Typography.Title><Typography.Paragraph type="secondary">从源代码与文档，到可追溯的知识与回答。<br/>登录企业身份服务，进入你获授权的知识空间。</Typography.Paragraph><ErrorNotice error={auth.error?new Error(auth.error):null}/>{auth.error&&<Alert type="error" message={auth.error}/>}<Button size="large" type="primary" onClick={()=>void auth.login()}>使用企业账号登录</Button><p className="muted">账号与密码由企业身份服务管理</p></div><div className="login-foot">版本化 Wiki · 精确引用 · 实时权限</div></div>;return <Shell/>;}
function Shell(){const {api,user,logout}=useAuth(),location=useLocation();const [collapsed,setCollapsed]=useState(false);const me=useResource('me',signal=>api.get<Principal>('/me',signal));const current='/'+(location.pathname.split('/')[1]||'chat');return <Layout className="app-shell"><Layout.Sider className="sidebar" width={224} collapsedWidth={76} collapsible collapsed={collapsed} trigger={null} breakpoint="lg" onBreakpoint={setCollapsed} theme="light"><Link className="brand" to="/chat"><span className="brand-mark"><SunOutlined/></span>{!collapsed&&<><strong>晴知</strong><small>KNOWLEDGE</small></>}</Link><Menu mode="inline" selectedKeys={[current]} items={[{key:'/chat',icon:<CommentOutlined/>,label:<Link to="/chat">问答</Link>},{key:'/spaces',icon:<BookOutlined/>,label:<Link to="/spaces">知识空间</Link>},{key:'/agents',icon:<RobotOutlined/>,label:<Link to="/agents">智能体</Link>},{key:'/reviews',icon:<CheckSquareOutlined/>,label:<Link to="/reviews">任务与审核</Link>},{key:'/settings',icon:<SettingOutlined/>,label:<Link to="/settings">设置</Link>}]} /><div className="sidebar-foot">{!collapsed&&<div className="workspace-label"><ApartmentOutlined/> 企业工作区<span>单租户 · 权限实时生效</span></div>}<Button type="text" aria-label={collapsed?'展开导航':'收起导航'} icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(!collapsed)}/></div></Layout.Sider><Layout className="main-layout" style={{marginLeft:collapsed?76:224}}><Layout.Header className="topbar"><Space><span className="live-dot"/> 企业知识平台 <Tag>V2</Tag></Space><Space><Avatar size="small" style={{background:'#e6efed',color:'#2b766d'}}>{String(user?.profile.name??user?.profile.preferred_username??'用').slice(0,1)}</Avatar><span className="account-name">{user?.profile.name??user?.profile.preferred_username??'当前用户'}</span><Button type="text" icon={<LogoutOutlined/>} onClick={()=>void logout()} aria-label="退出登录"/></Space></Layout.Header><Layout.Content className="page-content">{me.loading?<Skeleton active/>:me.error?<ErrorNotice error={me.error} retry={me.refresh}/>:me.data?<Routes><Route path="/" element={<Navigate replace to="/chat"/>}/><Route path="/auth/callback" element={<Navigate replace to="/chat"/>}/><Route path="/chat" element={<ChatPage/>}/><Route path="/spaces" element={<SpacesPage principal={me.data}/>}/><Route path="/spaces/:spaceId" element={<SpaceDetail/>}/><Route path="/spaces/:spaceId/pages/:pageId" element={<WikiPageDetail/>}/><Route path="/pages/:pageId" element={<WikiPageDetail/>}/><Route path="/agents" element={<AgentsPage/>}/><Route path="/reviews" element={<ReviewsPage/>}/><Route path="/settings/*" element={<SettingsPage principal={me.data}/>}/><Route path="/citations/:snapshotId" element={<CitationPage/>}/><Route path="*" element={<Result status="404" title="页面不存在" extra={<Link to="/chat">返回问答</Link>}/>}/></Routes>:null}</Layout.Content></Layout></Layout>;}
function CitationPage(){const {snapshotId=''}=useParams();const [params]=useSearchParams();return <div className="panel"><Typography.Title level={2}>原文快照</Typography.Title><CitationBody snapshotId={snapshotId} startLine={params.has('start')?Number(params.get('start')):undefined} endLine={params.has('end')?Number(params.get('end')):undefined}/></div>;}