// Generated by contract_generate.py; DO NOT EDIT.

package native

import (
	"github.com/wang550301463/sunny-knowledge/services/go/internal/channel"
	"github.com/wang550301463/sunny-knowledge/services/go/internal/iam"
	"github.com/wang550301463/sunny-knowledge/services/go/internal/platform"
)

type ChannelConfig = channel.Config
type ChannelConfigInput = channel.ConfigInput
type ChannelRunContext = channel.RunContext
type IamGroup = iam.Group
type IamPolicy = iam.Policy
type IamSpace = iam.Space
type IamUser = iam.User
type PlatformAuthorizationRequest = platform.AuthorizationRequest
type PlatformChannelConstraint = platform.ChannelConstraint
type PlatformDecision = platform.Decision
type PlatformPrincipal = platform.Principal
type PlatformResolved = platform.Resolved
type PlatformResource = platform.Resource
