import { test, expect, login, api, publicURL, workerID } from './fixtures.js';
import { randomUUID } from 'node:crypto';

test('real login, visible space modal, Markdown source, review and protected citation', async ({ page }) => {
  await login(page);
  await page.getByRole('link', { name: '知识空间', exact: true }).click();
  await page.getByRole('button', { name: /新建空间$/ }).click();
  const modal = page.getByRole('dialog', { name: '新建知识空间' });
  await expect(modal).toBeVisible();
  await expect(modal).toHaveCSS('opacity', '1');
  const name = '浏览器回归-' + randomUUID().slice(0, 8);
  await modal.getByLabel('空间名称').fill(name);
  const created = page.waitForResponse(r => r.url().endsWith('/api/v1/spaces') && r.request().method() === 'POST');
  await modal.getByRole('button', { name: /创建空间$/ }).click();
  const response = await created;
  expect(response.status()).toBe(201);
  const space = await response.json();
  await expect(modal).not.toBeVisible();
  const me = await api(page, 'GET', '/me');
  for (const action of ['read', 'write']) {
    await api(page, 'PUT', '/grants', { space_id: space.id, action, subjects: [me.subjects[0], 'service:' + workerID] });
  }
  await page.goto(publicURL + '/spaces/' + encodeURIComponent(space.id) + '?tab=sources');
  await page.getByRole('button', { name: /添加来源$/ }).click();
  const sourceModal = page.getByRole('dialog', { name: '添加数据来源' });
  await sourceModal.getByLabel('来源名称').fill('浏览器发布说明');
  await sourceModal.getByTitle('Git 仓库', { exact: true }).click();
  await page.getByTitle('Markdown 文档', { exact: true }).click();
  const sourcePath = 'docs/browser-' + randomUUID().slice(0, 8) + '.md';
  await sourceModal.getByLabel('相对文件路径').fill(sourcePath);
  const title = '发布验收-' + randomUUID().slice(0, 8);
  const text = '# ' + title + '\n先验证依赖证据，再审核发布。\n';
  await sourceModal.getByLabel('Markdown 原文').fill(text);
  const sourceCreated = page.waitForResponse(r => r.url().endsWith('/api/v1/sources') && r.request().method() === 'POST');
  await sourceModal.getByRole('button', { name: /添加来源$/ }).click();
  expect((await sourceCreated).status()).toBe(201);
  await expect(sourceModal).not.toBeVisible();
  await page.getByRole('button', { name: /预览与同步$/ }).click();
  await page.getByRole('button', { name: /预览原始快照$/ }).click();
  await expect(page.getByText(/预览文件 · 1 个/)).toBeVisible();
  const taskCreated = page.waitForResponse(r => r.url().endsWith('/sync') && r.request().method() === 'POST');
  await page.getByRole('button', { name: /启动同步$/ }).click();
  const taskResponse = await taskCreated;
  expect(taskResponse.status()).toBe(202);
  let task = await taskResponse.json();
  await expect.poll(async () => { task = await api(page, 'GET', '/tasks/' + task.id); return task.status; }, { timeout: 100_000 }).toBe('review_needed');
  const item = task.result.items[0];
  expect(item.proposal_id).toBeTruthy();
  await page.goto(publicURL + '/reviews');
  const row = page.getByRole('listitem').filter({ hasText: sourcePath });
  await row.getByRole('button', { name: '查看提案' }).click();
  const drawer = page.getByRole('dialog');
  await drawer.getByRole('tab', { name: '修改后预览', exact: true }).click();
  await expect(drawer.getByText('先验证依赖证据，再审核发布。', { exact: true }).first()).toBeVisible();
  await drawer.getByLabel('审核意见').fill('浏览器完整流程：核对来源后发布');
  await drawer.getByRole('button', { name: '批准并发布' }).click();
  await expect(drawer).not.toBeVisible();
  await page.goto(publicURL + '/pages/' + encodeURIComponent(item.page_id));
  await expect(page.getByRole('heading', { name: title }).first()).toBeVisible();
  const wiki = await api(page, 'GET', '/pages/' + encodeURIComponent(item.page_id));
  const evidence = wiki.revision.content.evidence[0];
  await page.goto(publicURL + '/citations/' + encodeURIComponent(evidence.revision_id) + '?start=1&end=2');
  await expect(page.getByText('先验证依赖证据，再审核发布。').first()).toBeVisible();
  await page.screenshot({ path: '/artifacts/browser-citation.png', fullPage: true });
  await api(page, 'PUT', '/grants', { space_id: space.id, resource_id: evidence.resource_id, action: 'read', subjects: [] });
  await page.reload();
  await expect(page.getByRole('alert').filter({ hasText: '权限不足' })).toBeVisible();
  await expect(page.getByText('先验证依赖证据，再审核发布。', { exact: true })).toHaveCount(0);
});

test('same-origin static deployment protects assets and supports narrow login', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const response = await page.goto(publicURL);
  expect(response.status()).toBe(200);
  expect(response.headers()['content-security-policy']).toContain("frame-ancestors 'none'");
  await expect(page.getByRole('button', { name: '使用企业账号登录' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: '/artifacts/browser-login-mobile.png', fullPage: true });
});
