import type { ReactNode } from 'react';
import { Alert, Button, Empty, Skeleton, Space, Tag, Typography } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import { ApiError, errorMessage } from '../api';
export function ErrorNotice({error,retry}:{error:unknown;retry?:()=>void}){if(!error)return null;return <Alert className="error-notice" showIcon type="error" message={errorMessage(error)} description={error instanceof ApiError?<span>错误代码：{error.code}{error.requestId&&<> · 请求编号：{error.requestId}</>}</span>:undefined} action={retry?<Button size="small" onClick={retry}>重试</Button>:undefined}/>;}
export function ResourceView<T>({resource,children,empty='暂无记录'}:{resource:{loading:boolean;error?:unknown;data?:T;refresh:()=>void};children:(data:T)=>ReactNode;empty?:string}){if(resource.loading)return <Skeleton active paragraph={{rows:4}}/>;if(resource.error)return <ErrorNotice error={resource.error} retry={resource.refresh}/>;if(resource.data===undefined)return <Empty description={empty}/>;return children(resource.data);}
export function PageHeader({eyebrow,title,description,extra}:{eyebrow?:string;title:string;description?:string;extra?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<Typography.Title level={2}>{title}</Typography.Title>{description&&<Typography.Paragraph type="secondary">{description}</Typography.Paragraph>}</div><div>{extra}</div></div>;}
export function RefreshButton({onClick}:{onClick:()=>void}){return <Button icon={<ReloadOutlined/>} onClick={onClick}>刷新</Button>;}
const statusLabels:Record<string,string>={valid:'有效',stale:'已过期',retracted:'已撤回',pending:'待审核',approved:'已批准',rejected:'已拒绝',active:'已启用',disabled:'已停用',retired:'已退役',passed:'测试通过',failed:'测试失败',untested:'未测试'};
export function StatusTag({status}:{status:string}){return <Tag color={['valid','approved','passed','active'].includes(status)?'green':['stale','pending','untested'].includes(status)?'gold':['retracted','rejected','failed'].includes(status)?'red':undefined}>{statusLabels[status]??status}</Tag>;}
export function Unavailable({title,description,error,retry}:{title:string;description:string;error?:unknown;retry?:()=>void}){return <div className="unavailable"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={<Space direction="vertical"><Typography.Text strong>{title}</Typography.Text><Typography.Text type="secondary">{description}</Typography.Text></Space>}/><ErrorNotice error={error} retry={retry}/></div>;}
export const formatDate=(value:string|undefined|null)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';